class_name Consts extends Object

enum {
	LAYER_WORLD = 1,
	LAYER_ROOFS = 2,
	LAYER_ITEM = 3,
	LAYER_USABLE = 4,
	LAYER_TRIGGER = 5,
	LAYER_INTERACTIVE_CHARACTER = 6,
	LAYER_MOVEABLE_PROP = 7,
	LAYER_WATER = 8,
	LAYER_ENEMY_CHARACTER = 9,
	LAYER_PLAYER = 10
}

const AUDIO_VOLUME_EFFECTS = 10
const AUDIO_BUS_EFFECTS = "Effects"

const COLOR_POSITIVE = Color.DARK_GREEN
const COLOR_NEGATIVE = Color.DARK_RED
